#
# The number of attempts RocketTeleport will try to find a suitable random landing zone.
#
Retries: 500
#
# Lists the block types that a random rocket will not teleport to.  Underscores should be used instead of spaces.
# Names are Material Types exactly as shown here: http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html
#
Exclusions:
  - LAVA
  - STATIONARY_LAVA
  - WATER
  - STATIONARY_WATER
#
# The sound that plays when a rocket is launched.  Underscores should be used instead of spaces.
# Names are Sounds exactly as shown here: http://jd.bukkit.org/rb/apidocs/org/bukkit/Sound.html
# Use NONE for no sound.
#
Sound:
  Type: EXPLODE
  Volume: 20
  Pitch: 0
#
# Timers (in approximate seconds)
#
# The delay timer sets the amount of time to wait before teleporting.
# Players must remain still and take no damage during this time.
#
# The cooldown timer prevents players from using teleports too quickly in succession.
#
# The invulnerability timer prevents players from taking damage immediately after teleporting.
#
# Cooldown and Delay only affect command based teleports, buttons and pressure plates will not apply.
#
Timer:
  Cooldown: 0
  Delay: 0
  Invulnerability: 4
#
# He's running.  He's running. Are they gonna catch him? We don't know.
# (approximate minutes)
#
EasterEggTimeout: 5
#
# Enable or Disable MCStats metrics logging
#
Metrics:
  Enabled: true
#
# Check for updates and notify the console or download and install (Check must be true to auto update)
# Interval defines the amount of time between checks in approximate minutes. 0 = Startup only
# ServerModsAPIKey is optional and can be found here https://dev.bukkit.org/home/servermods-apikey/
# DO NOT SHARE WITH ANYONE!  The API key will only be uploaded to BukkitDev, not the author of this plugin.
#
Update:
  Enabled: true
  Interval: 1440
  ServerModsAPIKey: null