name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.author}
website: ${project.url}
main: ${project.main}
softdepend: [Flags]
commands:
  rocketteleport:
    description: RocketTeleport command
    permission: rocketteleport.command
    aliases: rt
    usage: /rocketteleport <RocketType> [Radius]
  warp:
    description: Warps you to a pre-set location.
    permission: rocketteleport.warp
    aliases: warps
    usage: /warp <name>
  delwarp:
    description: Removes a warp location by warp name.
    permission: rocketteleport.warp.delete
    aliases: [remwarp, rmwarp]
    usage: /delwarp <name>
  setwarp:
    description: Defines a new warp location.
    permission: rocketteleport.warp.set
    aliases: createwarp
    usage: /setwarp <name>
permission:
  rocketteleport.command:
    description: Allows access to the rocketteleport command.
    default: op
  rocketteleport.admin.notifyupdate:
    description: Notifies players when an update to RocketTeleport is available.
    default: op
  rocketteleport.warp:
    description: Allows players to use the warp command.
    default: op
  rocketteleport.warp.set:
      description: Allows players to create warp locations.
      default: op
      children:
        rocketteleport.warp: true
  rocketteleport.warp.delete:
      description: Allows players to delete warp locations.
      default: op
      children:
        rocketteleport.warp: true