name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.author}
website: ${project.url}
main: ${project.main}
commands:
  rocketteleport:
    description: RocketTeleport command
    permission: rocketteleport.command
    alias: rt
    usage: /rocketteleport <RocketType> [Radius]
