name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.author}
website: ${project.url}
main: ${project.main}
commands:
  rocketteleport:
    description: RocketTeleport command
    permission: rocketteleport.command
    aliases: rt
    usage: /rocketteleport <RocketType> [Radius]
permission:
  rocketteleport.command:
    description: Allows access to the rocketteleport command.
    default: op
  rocketteleport.admin.notifyupdate:
    description: Notifies players when an update to RocketTeleport is available.
    default: op